# Generated by Django 4.0.2 on 2022-03-23 20:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('born', models.DateField()),
                ('dead', models.DateField()),
                ('bio', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('isbn13', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=3000)),
                ('rating', models.FloatField()),
                ('authors', models.ManyToManyField(to='website.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('books', models.ManyToManyField(to='website.Book')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('text_review', models.TextField(max_length=500)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField()),
                ('date_last_update', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('books', models.ManyToManyField(to='website.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.publisher'),
        ),
    ]
