# Generated by Django 4.0.2 on 2022-03-23 20:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_reading', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='currently_reading', to='website.list')),
                ('read', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='read', to='website.list')),
                ('to_read', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='to_read', to='website.list')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='website.Genres'),
        ),
    ]
